
server:
  port: 8083

spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: Mkirankumar@2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
