server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kirandb
    username: root
    password: Mkirankumar@2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: kirankumar6839
